version: '3'

services:
  tinyllama-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5020:5020"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
